version: '2.1'
services:
  kafka:
    build:
      context: .
    image: mmaia/kafka:0.10.2.1
    container_name: kafka
    ulimits:
          memlock:
            soft: -1
            hard: -1
          nofile:
            soft: 65536
            hard: 65536
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      ADVERTISED_HOST: 127.0.0.1  # single node so can bind to localhost..
      ADVERTISED_PORT: 9092
      JMX_PORT: 9999